version: 1.0.{build}
before_build:
- ps: nuget restore TravelShare.sln
build:
  project: TravelShare.sln
  verbosity: minimal
  
environment:
  COVERALLS_REPO_TOKEN:
    secure:295TQXG8NTjLm4vGIRI7lu23E3MMdhavft+nf2PIdPX95bZjmT2zFnw8GAxIpc9R
after_test: 
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.ConsoleRunner.3.6.1\tools\nunit3-console.exe" -targetargs:"/domain:single Tests\TravelShare.Web.Controllers.Tests\bin\Debug\TravelShare.Web.Controllers.Tests.dll" -output:cover.xml
  - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover cover.xml
